// Cude.new - [[path]].ts (Cude product surface, 2026)
import type { ServerBuild } from '@remix-run/cloudflare';
import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';
// Generated by `npm run build`. Keeping this static lets Wrangler bundle the
// Remix server instead of trying to resolve a runtime-relative path.
// @ts-ignore The generated module is absent in a clean typecheck workspace.
import * as serverBuild from '../build/server/index.js';

export const onRequest: PagesFunction = async (context) => {
  const handler = createPagesFunctionHandler({
    build: serverBuild as unknown as ServerBuild,
  });

  return handler(context);
};
